---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AUTOMATED: pwshCloudCommands - infrastructure resource deployment'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service being deployed. Used for Developer AWS Account Resource Names.

  ResourceType:
    Type: String
    Description: Determine the type of resource that will be deployed
    AllowedValues:
      - core
      - dev
      - test
      - prod

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-websiteconfiguration.html
  PSCCFinalXMLBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      # AccelerateConfiguration: AccelerateConfiguration
      AccessControl: BucketOwnerFullControl
      # AnalyticsConfigurations:
      #   - AnalyticsConfiguration
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # BucketName: !Sub ${ServiceName}-${AWS::AccountId}-website
      # CorsConfiguration:
      #   CorsConfiguration
      # IntelligentTieringConfigurations:
      #   - IntelligentTieringConfiguration
      # InventoryConfigurations:
      #   - InventoryConfiguration
      # LifecycleConfiguration:
      #   Rules:
      #       -
      #         AbortIncompleteMultipartUpload:
      #           DaysAfterInitiation: 7
      #         Status: Enabled
      #         Transitions:
      #           -
      #             StorageClass: GLACIER
      #             TransitionInDays: 30
      # LoggingConfiguration:
      #   DestinationBucketName: !Ref StaticWebSiteLoggingBucket
      #   LogFilePrefix: '/logs/website/'
      # MetricsConfigurations:
      #   - MetricsConfiguration
      # NotificationConfiguration:
      #   TopicConfigurations:
      #     -
      #       Event: s3:ObjectCreated:*
      #       Topic: !Ref UpdateSNSTopic
      # ObjectLockConfiguration:
      #   ObjectLockConfiguration
      # ObjectLockEnabled: Boolean
      # OwnershipControls:
      #   OwnershipControls
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # ReplicationConfiguration:
      #   ReplicationConfiguration
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: ResourceType
          Value: !Ref ResourceType
      # VersioningConfiguration:
      #   VersioningConfiguration
      # WebsiteConfiguration:
      #   IndexDocument: index.html
        # ErrorDocument: error.html
        # RoutingRules:
        #   - RoutingRuleCondition:
        #       HttpErrorCodeReturnedEquals: '404'
        #       KeyPrefixEquals: out1/
        #     RedirectRule:
        #       HostName: ec2-11-22-333-44.compute-1.amazonaws.com
        #       ReplaceKeyPrefixWith: report-404/

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
  # https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteAccessPermissionsReqd.html
  PSCCFinalXMLBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PSCCFinalXMLBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowCloudFrontServicePrincipalReadOnly'
            Effect: 'Allow'
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${PSCCFinalXMLBucket}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${PSCCCloudFrontDistribution}'
          - Sid: 'AllowLegacyOAIReadOnly'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::cloudfront:user/CloudFront Origin Access Identity ${PSCCCloudFrontOriginAccessIdentity}'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${PSCCFinalXMLBucket}/*'

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-websiteconfiguration.html
  PSCCCloudFrontLogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      # AccelerateConfiguration: AccelerateConfiguration
      AccessControl: BucketOwnerFullControl
      # AnalyticsConfigurations:
      #   - AnalyticsConfiguration
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # BucketName: !Sub ${ServiceName}-${AWS::AccountId}-website
      # CorsConfiguration:
      #   CorsConfiguration
      # IntelligentTieringConfigurations:
      #   - IntelligentTieringConfiguration
      # InventoryConfigurations:
      #   - InventoryConfiguration
      # LifecycleConfiguration:
      #   Rules:
      #       -
      #         AbortIncompleteMultipartUpload:
      #           DaysAfterInitiation: 7
      #         Status: Enabled
      #         Transitions:
      #           -
      #             StorageClass: GLACIER
      #             TransitionInDays: 30
      # LoggingConfiguration:
      #   DestinationBucketName: !Ref StaticWebSiteLoggingBucket
      #   LogFilePrefix: '/logs/website/'
      MetricsConfigurations:
        - Id: EntireBucket
      # NotificationConfiguration:
      #   TopicConfigurations:
      #     -
      #       Event: s3:ObjectCreated:*
      #       Topic: !Ref UpdateSNSTopic
      # ObjectLockConfiguration:
      #   ObjectLockConfiguration
      # ObjectLockEnabled: Boolean
      # OwnershipControls:
      #   OwnershipControls
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # ReplicationConfiguration:
      #   ReplicationConfiguration
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: ResourceType
          Value: !Ref ResourceType
      # VersioningConfiguration:
      #   VersioningConfiguration
      # WebsiteConfiguration:
      #   IndexDocument: index.html
        # ErrorDocument: error.html
        # RoutingRules:
        #   - RoutingRuleCondition:
        #       HttpErrorCodeReturnedEquals: '404'
        #       KeyPrefixEquals: out1/
        #     RedirectRule:
        #       HostName: ec2-11-22-333-44.compute-1.amazonaws.com
        #       ReplaceKeyPrefixWith: report-404/

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
  PSCCCloudFrontLogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PSCCCloudFrontLogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: LoggingBucketPermissions
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${PSCCCloudFrontLogBucket}/AWSLogs/${AWS::AccountId}/*'

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-originaccesscontrol.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originaccesscontrol-originaccesscontrolconfig.html
  # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html
  # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-origin.html
  PSCCCloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: pwshCloudCommands CloudFront Origin Access Control
        Name: pscc-origin-access-control
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-PSCCCloudFrontOriginAccessIdentity.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-PSCCCloudFrontOriginAccessIdentity-PSCCCloudFrontOriginAccessIdentityconfig.html
  PSCCCloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref PSCCFinalXMLBucket

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html
  # https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/template.yaml
  # https://hackernoon.com/how-to-configure-cloudfront-using-cloudformation-template-2c263u56
  PSCCCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        # Aliases:
        #   - String
        # CacheBehaviors:
        #   - CacheBehavior
        # CNAMEs:
        #   - String
        Comment: 'pwshCloudCommands CloudFront for PowerShell Cloud XML'
        # CustomErrorResponses:
        #   - ErrorCode: 403 # not found
        #     ResponseCode: 404
        #     ResponsePagePath: "/index.html"
        # CustomOrigin:
        #   LegacyCustomOrigin
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            # - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            # - OPTIONS
          # CachePolicyId: String
          Compress: true
          DefaultTTL: 3600 # in seconds
          # FieldLevelEncryptionId: String
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          # FunctionAssociations:
          #   - FunctionAssociation
          # LambdaFunctionAssociations:
          #   - LambdaFunctionAssociation
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          # OriginRequestPolicyId: String
          # RealtimeLogConfigArn: String
          # ResponseHeadersPolicyId: String
          # SmoothStreaming: Boolean
          TargetOriginId: s3origin
          # TrustedKeyGroups:
          #   - String
          # TrustedSigners:
          #   - String
          ViewerProtocolPolicy: 'https-only'
        # DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: http2
        # IPV6Enabled: Boolean
        Logging:
          Bucket: !Sub ${PSCCCloudFrontLogBucket}.s3.amazonaws.com
          # IncludeCookies: Boolean
          Prefix: pwshcloudcommands
        # OriginGroups:
        #   OriginGroups
        Origins:
          - DomainName: !GetAtt "PSCCFinalXMLBucket.DomainName"
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${PSCCCloudFrontOriginAccessIdentity}"
        PriceClass: PriceClass_100
        # Restrictions:
        #   Restrictions
        # S3Origin:
        #   LegacyS3Origin
        # ViewerCertificate:
        #   ViewerCertificate
        # WebACLId: String
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: ResourceType
          Value: !Ref ResourceType

Outputs:
  PSCCFinalXMLBucketName:
    Description: Name of the PSCCFinalXMLBucket Amazon S3 bucket
    Value: !Ref PSCCFinalXMLBucket
    Export:
      Name: !Sub ${ServiceName}-PSCCFinalXMLBucket

  PSCCFinalXMLBucketARN:
    Description: ARN of the PSCCFinalXMLBucket Amazon S3 bucket
    Value: !GetAtt PSCCFinalXMLBucket.Arn
    Export:
      Name: !Sub ${ServiceName}-PSCCFinalXMLBucketARN

  PSCCCloudFrontLogBucketARN:
    Description: ARN of the PSCCCloudFrontLogBucket Amazon S3 bucket
    Value: !GetAtt PSCCCloudFrontLogBucket.Arn
    Export:
      Name: !Sub ${ServiceName}-PSCCCloudFrontLogBucketARN

  PSCCCloudFrontDistributionDomain:
    Description: The domain of the PSCCCloudFrontDistribution
    Value: !GetAtt PSCCCloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${ServiceName}-PSCCCloudFrontDistributionDomain
