<#
.SYNOPSIS
    Removes stop words from provided input text.
.DESCRIPTION
    Parses provided input text and removes stop words.
.EXAMPLE
    Remove-StopWord -SearchInput $searchInput

    Returns the input text with stop words removed.
.OUTPUTS
    System.String
.NOTES
    Author: Jake Morrison - @jakemorrison - https://www.techthoughts.info/
.COMPONENT
    pwshCloudCommands
#>
function Remove-StopWord {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseShouldProcessForStateChangingFunctions", "")]
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true,
            Position = 0,
            HelpMessage = 'TBD')]
        [string[]]$SearchInput
    )

    $stopWords = @(
        'a'
        'about'
        'above'
        'actually'
        'after'
        'again'
        'against'
        'all'
        'almost'
        'also'
        'although'
        'always'
        'am'
        'an'
        'and'
        'any'
        'are'
        'as'
        'at'
        'be'
        'became'
        'because'
        'become'
        'been'
        'before'
        'being'
        'below'
        'between'
        'both'
        'but'
        'by'
        'can'
        'cannot'
        'could'
        'did'
        'do'
        'does'
        'doing'
        'down'
        'during'
        'each'
        'either'
        'else'
        'few'
        'for'
        'from'
        'further'
        'had'
        'has'
        'have'
        'having'
        'he'
        'hence'
        'her'
        'here'
        'hers'
        'herself'
        'him'
        'himself'
        'his'
        'how'
        'i'
        'if'
        'in'
        'into'
        'is'
        'it'
        'its'
        'itself'
        'just'
        'may'
        'maybe'
        'me'
        'might'
        'mine'
        'more'
        'most'
        'must'
        'my'
        'myself'
        'neither'
        'no'
        'nor'
        'not'
        'of'
        'off'
        'oh'
        'ok'
        'on'
        'once'
        'only'
        'or'
        'other'
        'ought'
        'our'
        'ours'
        'ourselves'
        'out'
        'over'
        'own'
        'same'
        'she'
        'so'
        'some'
        'such'
        'than'
        'that'
        'the'
        'their'
        'theirs'
        'them'
        'themselves'
        'then'
        'there'
        'these'
        'they'
        'this'
        'those'
        'through'
        'to'
        'too'
        'under'
        'very'
        'was'
        'we'
        'were'
        'what'
        'whenever'
        'whereas'
        'wherever'
        'whether'
        'who'
        'whoever'
        'whom'
        'whose'
        'why'
        'will'
        'with'
        'within'
        'without'
        'would'
        'yes'
        'yet'
        'you'
        'your'
        'yours'
        'yourself'
        'yourselves'
    )

    $cleanInput = $SearchInput | Where-Object { $stopWords -notcontains $_ }

    return $cleanInput

} #Remove-StopWord
